// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class ManageUser {
		
		protected System.Web.UI.WebControls.Content mainContent;
		
		public new AutoAssess.Web.MasterPage Master {
			get {
				return ((AutoAssess.Web.MasterPage)(base.Master));
			}
		}
	}
}
