// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class AddHostToProfile {
		
		protected System.Web.UI.WebControls.Content mainContent;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divCreateProfileExplanation;
		
		protected System.Web.UI.WebControls.Button btnStartVerification;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divAddHostContainer;
		
		protected System.Web.UI.WebControls.TextBox txtHostURL;
		
		protected System.Web.UI.WebControls.Label lblDomain;
		
		protected System.Web.UI.WebControls.Button btnAddHost;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divMultiEmailContainer;
		
		protected System.Web.UI.WebControls.Label lblMultiEmailContainerHeader;
		
		protected System.Web.UI.WebControls.DropDownList ddlWhoisEmail;
		
		protected System.Web.UI.WebControls.Button btnSendVerification;
		
		protected System.Web.UI.WebControls.TextBox txtEmailKey;
		
		protected System.Web.UI.WebControls.Button btnVerifyEmailKey;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divVerificationFileContainer;
		
		protected System.Web.UI.WebControls.Label lblVerificationFileHeader;
		
		protected System.Web.UI.WebControls.Label lblVerificationURL;
		
		protected System.Web.UI.WebControls.Label lblFilename;
		
		protected System.Web.UI.WebControls.Label lblFileContents;
		
		protected System.Web.UI.WebControls.Button btnVerifyFile;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divFinishUpContainer;
		
		protected System.Web.UI.WebControls.Button btnCreateProfile;
		
		public new AutoAssess.Web.MasterPage Master {
			get {
				return ((AutoAssess.Web.MasterPage)(base.Master));
			}
		}
	}
}
