// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class CreateScan {
		
		protected System.Web.UI.WebControls.TextBox txtProfileName;
		
		protected System.Web.UI.WebControls.TextBox txtProfileRange;
		
		protected System.Web.UI.WebControls.TextBox txtScanName;
		
		protected System.Web.UI.WebControls.RadioButtonList rblWebAssessmentOptions;
		
		protected System.Web.UI.WebControls.Button btnBasicWebAssessment;
		
		protected System.Web.UI.WebControls.RadioButtonList rblBruteforceOptions;
		
		protected System.Web.UI.WebControls.Button btnBruteforce;
		
		protected System.Web.UI.WebControls.RadioButtonList rblGeneralAssessmentOptions;
		
		protected System.Web.UI.WebControls.Button btnBasicVulnAssessment;
	}
}
