// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class CreditCardPayment {
		
		protected System.Web.UI.WebControls.Content mainContent;
		
		protected System.Web.UI.WebControls.TextBox txtFirstName;
		
		protected System.Web.UI.WebControls.TextBox txtLastName;
		
		protected System.Web.UI.WebControls.TextBox txtCreditCard;
		
		protected System.Web.UI.WebControls.TextBox txtSecurityCode;
		
		protected System.Web.UI.WebControls.TextBox txtExpiryDate;
		
		protected System.Web.UI.WebControls.TextBox txtStreetAddress;
		
		protected System.Web.UI.WebControls.TextBox txtCity;
		
		protected System.Web.UI.WebControls.TextBox txtState;
		
		protected System.Web.UI.WebControls.TextBox txtZIP;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
		
		public new AutoAssess.Web.MasterPage Master {
			get {
				return ((AutoAssess.Web.MasterPage)(base.Master));
			}
		}
	}
}
