// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content contentDefault;
		
		protected System.Web.UI.WebControls.Label lblNumberOfProfiles;
		
		protected System.Web.UI.WebControls.Label lblProfilesHealth;
		
		protected System.Web.UI.WebControls.Label lblCoverage;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divEvents;
		
		protected System.Web.UI.WebControls.Calendar calendar1;
	}
}
