// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class EditUserProfile {
		
		protected System.Web.UI.WebControls.Content mainContent;
		
		protected System.Web.UI.WebControls.TextBox txtUsername;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.TextBox txtConfirmPassword;
		
		protected System.Web.UI.WebControls.TextBox txtEmailAddress;
		
		protected System.Web.UI.WebControls.TextBox txtFirstName;
		
		protected System.Web.UI.WebControls.TextBox txtMiddleName;
		
		protected System.Web.UI.WebControls.TextBox txtLastName;
		
		protected System.Web.UI.WebControls.TextBox txtPrimaryPhone;
		
		protected System.Web.UI.WebControls.TextBox txtSecondaryPhone;
		
		protected System.Web.UI.WebControls.Button btnEditUser;
		
		public new AutoAssess.Web.MasterPage Master {
			get {
				return ((AutoAssess.Web.MasterPage)(base.Master));
			}
		}
	}
}
