// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class MasterPage {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divMenuItems;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divRightMenu;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divProfiles;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divUserMenu;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divContent;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder main;
	}
}
