// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class RemediationDetails {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblSummary;
		
		protected System.Web.UI.WebControls.Label lblScore;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divRisks;
		
		protected System.Web.UI.WebControls.Label lblAuthentication;
		
		protected System.Web.UI.WebControls.Label lblAvailabilityImpact;
		
		protected System.Web.UI.WebControls.Label lblComplexity;
		
		protected System.Web.UI.WebControls.Label lblConfidentialityImpact;
		
		protected System.Web.UI.WebControls.Label lblIntegrityImpact;
		
		protected System.Web.UI.WebControls.Label lblVulnVector;
		
		protected System.Web.UI.WebControls.Label lblPatchTitle;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divPatchLinkList;
		
		protected System.Web.UI.WebControls.Label lblVendorTitle;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divVendorLinkList;
		
		protected System.Web.UI.WebControls.Label lblOtherTitle;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divOtherLinkList;
	}
}
