// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class UserProfile {
		
		protected System.Web.UI.WebControls.Label lblUsername;
		
		protected System.Web.UI.WebControls.Label lblEmailAddress;
		
		protected System.Web.UI.WebControls.Label lblFirstName;
		
		protected System.Web.UI.WebControls.Label lblMiddleName;
		
		protected System.Web.UI.WebControls.Label lblLastName;
		
		protected System.Web.UI.WebControls.Label lblPrimaryPhone;
		
		protected System.Web.UI.WebControls.Label lblSecondaryPhone;
	}
}
