// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class ViewProfile {
		
		protected System.Web.UI.WebControls.GridView gvHosts;
		
		protected System.Web.UI.WebControls.Button btnGotoHost;
		
		protected System.Web.UI.WebControls.Label lblHostname;
		
		protected System.Web.UI.WebControls.Label lblOverallRisk;
		
		protected System.Web.UI.WebControls.Label lblNessusGrade;
		
		protected System.Web.UI.WebControls.Label lblNexposeGrade;
		
		protected System.Web.UI.WebControls.Label lblOpenVASGrade;
		
		protected System.Web.UI.WebControls.Label lblMetasploitGrade;
		
		protected System.Web.UI.WebControls.Label lblExploitable;
	}
}
