// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class ViewProfiles {
		
		protected System.Web.UI.WebControls.GridView gvProfiles;
		
		protected System.Web.UI.WebControls.Button lnkViewProfile;
		
		protected System.Web.UI.WebControls.Button btnScheduleNewRun;
		
		protected System.Web.UI.WebControls.Button btnCreateScanFromProfile;
		
		protected System.Web.UI.WebControls.Button btnDeleteProfile;
	}
}
