// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class ViewHost {
		
		protected System.Web.UI.WebControls.Label lblHostname;
		
		protected System.Web.UI.WebControls.Label lblIPv4;
		
		protected System.Web.UI.WebControls.Label lblDeviceType;
		
		protected System.Web.UI.WebControls.Label lblOS;
		
		protected System.Web.UI.WebControls.Label lblNetworkDistance;
		
		protected System.Web.UI.WebControls.GridView gvPorts;
		
		protected System.Web.UI.WebControls.Button btnViewPortDetails;
	}
}
