// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web {
	
	
	public partial class ViewPortDetails {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divNiktoResults;
		
		protected System.Web.UI.WebControls.Label lblNiktoResultsHeader;
		
		protected System.Web.UI.WebControls.Label lblNiktoResults;
		
		protected System.Web.UI.WebControls.Label lblOpenVASPortResults;
		
		protected System.Web.UI.WebControls.GridView gvOpenVASPortResults;
		
		protected System.Web.UI.WebControls.Label lblNessusPortResults;
		
		protected System.Web.UI.WebControls.GridView gvNessusPortResults;
		
		protected System.Web.UI.WebControls.Label lblNexposePortResults;
		
		protected System.Web.UI.WebControls.GridView gvNexposePortResults;
		
		protected System.Web.UI.WebControls.Label lblSNMPResultsHeader;
		
		protected System.Web.UI.WebControls.Label lblSNMPResults;
		
		protected System.Web.UI.WebControls.Label lblSMBScanHeader;
		
		protected System.Web.UI.WebControls.Label lblSMBScan;
		
		protected System.Web.UI.WebControls.Label lblSQLInjections;
		
		protected System.Web.UI.WebControls.GridView gvSQLInjections;
		
		protected System.Web.UI.WebControls.Label lblMethod;
		
		protected System.Web.UI.WebControls.Label lblKnownExploitable;
		
		protected System.Web.UI.WebControls.Label lblURL;
		
		protected System.Web.UI.WebControls.Label lblParameter;
		
		protected System.Web.UI.WebControls.Label lblPossibleSQLInjections;
		
		protected System.Web.UI.WebControls.GridView gvPossibleInjectionPoints;
		
		protected System.Web.UI.WebControls.Label lblPossibleMethod;
		
		protected System.Web.UI.WebControls.Label lblPossibleURL;
		
		protected System.Web.UI.WebControls.Label lblPossibleParameter;
		
		protected System.Web.UI.WebControls.Label lblXSS;
		
		protected System.Web.UI.WebControls.GridView gvXSS;
		
		protected System.Web.UI.WebControls.Label lblIncludes;
		
		protected System.Web.UI.WebControls.GridView gvIncludes;
		
		protected System.Web.UI.WebControls.Label lblCommandExecution;
		
		protected System.Web.UI.WebControls.GridView gvCommandExecution;
	}
}
