// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web.Admin.Admin {
	
	
	public partial class CreateClient {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
	}
}
