// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AutoAssess.Web.Admin {
	
	
	public partial class CreateScan {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtHosts;
		
		protected System.Web.UI.WebControls.ListBox lstHosts;
		
		protected System.Web.UI.WebControls.TextBox txtProfileName;
		
		protected System.Web.UI.WebControls.CheckBox chkBruteforce;
		
		protected System.Web.UI.WebControls.CheckBox chkSQLMap;
		
		protected System.Web.UI.WebControls.CheckBox chkDSXS;
		
		protected System.Web.UI.WebControls.CheckBox chkOpenVAS;
		
		protected System.Web.UI.WebControls.CheckBox chkNessus;
		
		protected System.Web.UI.WebControls.CheckBox chkNexpose;
		
		protected System.Web.UI.WebControls.CheckBox chkMetasploit;
		
		protected System.Web.UI.WebControls.CheckBox chkMetasploitDiscovers;
		
		protected System.Web.UI.WebControls.CheckBox chkMetasploitBruteforces;
		
		protected System.Web.UI.WebControls.TextBox txtScanName;
		
		protected System.Web.UI.WebControls.DropDownList ddlUser;
		
		protected System.Web.UI.WebControls.Button btnCreateScan;
	}
}
